version: '3.9'

services:
  main:
    build: .
    container_name: main
    volumes:
      - ./app/src:/app/src
      - ./app/data:/app/data
      - ./app/clean_data_set:/app/clean_data_set
    restart: "on-failure"
    depends_on:
      pgdatabase:
        condition: service_healthy

  pgdatabase:
    image: postgres:15
    container_name: pgdatabase
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: trades_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 5s
      retries: 5
      timeout: 5s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - pgdatabase
    restart: on-failure

volumes:
  pg_data:
